Feature/milestone 2
AshakaE/react-math-app pull request #2
Opened 2021-05-13 19:26 UTC by AshakaE

2021-05-13 20:28 UTC, addod19 commented
## Status: Invalid!!! :red_circle: 

Hi @AshakaE, I will have to mark this project as invalid because the linter is not set up to check for errors. Kindly fix that and submit another code review

2021-05-13 21:38 UTC, Forison requested changes
## Status::Changes required❌.

# 👋  @AshakaE 

#### Good job on this one so far, the pull request is very professional, Good job on the use of React fragment and validating all your props💪 .

* [x] App.js renders the Display and ButtonPanel components ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/app/appFunctionalComponent.png)). Currently you are only rendering Display.jsx.

#### That is it kindly make the change and submit a re-review🤗.

#### Happy coding😎 

Addo Forison

2021-05-13 21:38 UTC, Forison commented on src/components/Button.js
> +  const { name } = props;
**[Optional]**
We can destructure `name` at the argument level, that way we avoid line 5.

2021-05-13 21:41 UTC, Forison requested changes

2021-05-13 21:41 UTC, Forison commented on src/components/App.css
> +.App {
* [ ] Kindly remove this code, there are no requirement for styling, at least not for now. unrelated code must be removed.

2021-05-14 08:26 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @AshakaE, the comment from the previous review was not addressed. I will point it out here as well so we can address it :slightly_smiling_face: Kindly check the comments below:
- The App.js file should render 2 components, ie. the Display component which we have currently, and the ButtonPanel component which needs to be rendered in the App component

Once this is fixed, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-05-14 10:20 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi @AshakaE, congratulations on this milestone :fireworks: Now the ButtonPanel is rendered in the App component :1st_place_medal: 

I hereby approve the project :smile: 
Kindly go ahead and merge into the development branch, do not forget to submit the project completion form
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-05-14 10:34 UTC, merged